### PR TITLE
Update to v3.7.10

### PR DESCRIPTION
**Pull request by oie1**
yes
(edited to remove the changelog which mentioned a couple of people I'm very sorry)

### CODE REVIEW

**Comment by oie1** [comment]
!testme

**Comment by cswimr** [comment]
Hi there (I was mentioned because you copy pasted the changelog)

**Comment by oie1** [comment]
> Hi there (I was mentioned because you copy pasted the changelog)

sorry!

**Comment by oie1** [comment]
sorry I made mistake a big, the !testme will probably fail due to the manifest thing, I leave

**Comment by ari-party** [comment]
😿

**Comment by oie1** [comment]
ok

**Comment by oie1** [comment]
stop sadding me :(

**Comment by oie1** [comment]
😿

**Pull request closed without merging**
